# Generated by Django 4.2.1 on 2023-05-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_like_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='Post',
            new_name='post',
        ),
    ]
