# Generated by Django 4.2.1 on 2023-05-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='default_images/post_default.jpg', null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_images/avatar.svg', null=True, upload_to='avatars/'),
        ),
    ]
