# Generated by Django 4.2.1 on 2023-05-24 18:31

from django.db import migrations, models


def update_avatar_path(apps, schema_editor):
    User = apps.get_model('base', 'User')
    for user in User.objects.all():
        if user.avatar and 'images' not in user.avatar.path:
            new_path = f'images/default_images/{user.avatar.name}'
            user.avatar.name = new_path
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_post_post_image_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/default_images/avatar.svg', null=True, upload_to='avatars/'),
        ),
        migrations.RunPython(update_avatar_path),
    ]
