# Generated by Django 4.2.1 on 2023-05-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_images/avatar.svg', null=True, upload_to='avatars/'),
        ),
    ]
