# Generated by Django 4.2.1 on 2023-05-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='post_default', upload_to='post_images/'),
        ),
    ]
