# Generated by Django 4.2.1 on 2023-05-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='images/default_images/post_default.jpg', null=True, upload_to='post_images/'),
        ),
    ]
